// <auto-generated />
namespace GesStaDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remove_Dispo_In_Utiliser_Add_To_Mat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_Dispo_In_Utiliser_Add_To_Mat));
        
        string IMigrationMetadata.Id
        {
            get { return "202109211516287_Remove_Dispo_In_Utiliser_Add_To_Mat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
