// <auto-generated />
namespace GesStaDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_TypeDeStage_From_Fk_To_Attr_And_From_Int_To_Str : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_TypeDeStage_From_Fk_To_Attr_And_From_Int_To_Str));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181429317_Change_TypeDeStage_From_Fk_To_Attr_And_From_Int_To_Str"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
