// <auto-generated />
namespace GesStaDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_New_Attr_Stage_Varchar_To_Demande : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_New_Attr_Stage_Varchar_To_Demande));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181740504_Add_New_Attr_Stage_Varchar_To_Demande"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
