// <auto-generated />
namespace GesStaDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Offre_In_Demande_Fk_TypeDeStage_As_Int11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Offre_In_Demande_Fk_TypeDeStage_As_Int11));
        
        string IMigrationMetadata.Id
        {
            get { return "202109190854568_Add_Offre_In_Demande_Fk_TypeDeStage_As_Int11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
